const suiteData = [
    {"text":"a₁","normalForm":{"type":"variable","name":"a₁"}},
    {"text":"a₁b₁","normalForm":{"type":"application","left":{"type":"variable","name":"a₁"},"right":{"type":"variable","name":"b₁"}}},
    {"text":"(λabc.d)","normalForm":{"type":"function","argument":"a","body":{"type":"function","argument":"b","body":{"type":"function","argument":"c","body":{"type":"variable","name":"d"}}}}},
    {"text":"(λa.a)b","normalForm":{"type":"variable","name":"b"}},
    {"text":"(λa.a)λb.b","normalForm":{"type":"function","argument":"b","body":{"type":"variable","name":"b"}}},
    {"text":"((λb.b)c)((λd.d)e)","normalForm":{"type":"application","left":{"type":"variable","name":"c"},"right":{"type":"variable","name":"e"}}},
    {"text":"(λab.a(a(a(a(a(a(ab)))))))(λn.λf.λx.f(nfx))(λcd.c(c(c(c(c(c(c(c(cd)))))))))","normalForm":{"type":"function","argument":"f","body":{"type":"function","argument":"x","body":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"variable","name":"x"}}}}}}}}}}}}}}}}}}}},
    {"text":"(λgh.g(g(gh)))(λab.b((λlm.l(λn.λf.λx.f(nfx))m)a)λde.e)(λij.i(i(ij)))","normalForm":{"type":"function","argument":"b","body":{"type":"application","left":{"type":"application","left":{"type":"variable","name":"b"},"right":{"type":"function","argument":"m","body":{"type":"function","argument":"e","body":{"type":"variable","name":"e"}}}},"right":{"type":"function","argument":"d","body":{"type":"function","argument":"e","body":{"type":"variable","name":"e"}}}}}},
    {"text":"(λab.b((λlm.l(λn.λf.λx.f(nfx))m)a)λde.e)(λgh.g(g(gh)))(λij.i(i(ij)))","normalForm":{"type":"function","argument":"f","body":{"type":"function","argument":"x","body":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"variable","name":"x"}}}}}}}}}}}}},
    {"text":"(λn.λf.λx.n((λf.λp.(λx.λy.λf.fxy)(f(p(λa.λb.a)))(p(λa.λb.a)))f)((λx.λy.λf.fxy)xx)(λa.λb.b))(λf.λn.f(f(fn)))","normalForm":{"type":"function","argument":"f","body":{"type":"function","argument":"x","body":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"variable","name":"x"}}}}}},
    {"text":"(λa.λb.b(λn.λf.λx.n((λf.λp.(λx.λy.λf.fxy)(f(p(λa.λb.a)))(p(λa.λb.a)))f)((λx.λy.λf.fxy)xx)(λa.λb.b))a)((λn.λf.λx.f(nfx))((λn.λf.λx.f(nfx))((λn.λf.λx.f(nfx))((λn.λf.λx.f(nfx))((λn.λf.λx.f(nfx))((λn.λf.λx.f(nfx))(λf.λn.n)))))))((λn.λf.λx.f(nfx))((λn.λf.λx.f(nfx))((λn.λf.λx.f(nfx))((λn.λf.λx.f(nfx))(λf.λn.n)))))","normalForm":{"type":"function","argument":"f","body":{"type":"function","argument":"x","body":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"application","left":{"type":"variable","name":"f"},"right":{"type":"variable","name":"x"}}}}}},
];

export default suiteData;
